pipeline { 
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.11-slim
    command: ['sleep']
    args: ['infinity']
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
'''
        }
    }
    stages { 
        stage('build') { 
            steps { 
                container('python') {
                    echo 'Compiling vote app.' 
                    dir('vote') {
                        sh "pip install -r requirements.txt"
                    } 
                }
            } 
        } 
        stage('test') { 
            steps { 
                container('python') {
                    echo 'Running Unit Tests on vote app.' 
                    dir('vote') { 
                        sh "pip install -r requirements.txt"
                        sh 'nosetests -v'
                    } 
                }
            } 
        } 
        stage('docker-package') {
            steps {
                container('docker') {
                    echo 'Packaging vote app with docker'
                    script {
                        withEnv(['DOCKER_HOST=tcp://localhost:2375']) {
                            docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                                // ./vote is the path to the Dockerfile that Jenkins will find from the Github repo
                                def voteImage = docker.build("xxxx/vote:v${env.BUILD_ID}", "./vote")
                                voteImage.push()
                                voteImage.push("${env.BRANCH_NAME}")
                                voteImage.push("latest")
                            }
                        }
                    }
                }
            }
        }
    } 
    post {
        always {
            echo 'Pipeline for vote is complete'
        }
    }
}
