pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.8.7-openjdk-18-slim
    command: ['sleep']
    args: ['infinity']
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
'''
        }
    }
    stages {
        stage("build") {
            when {
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Compiling worker app..'
                    dir('worker') {
                        sh 'mvn compile'
                    }
                }
            }
        }
        stage("test") {
            when {
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Running unit tests on worker app..'
                    dir('worker') {
                        sh 'mvn clean test'
                    }
                }
            }
        }
        stage("package") {
            when { 
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Packaging worker app into a jarfile'
                    dir('worker') {
                        sh 'mvn package -DskipTests'
                        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    }
                }
            }
        }
        stage('docker-package') {
            when {
                changeset "**/worker/**"
                branch 'main'
            }
            steps {
                container('docker') {
                    echo 'Packaging worker app with docker'
                    script {
                        // Point the Docker client to the Docker-in-Docker daemon
                        withEnv(['DOCKER_HOST=tcp://localhost:2375']) {
                            docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') { 
                                def workerImage = docker.build("emmiduh93/worker:v${env.BUILD_ID}", "./worker")
                                workerImage.push("${env.BRANCH_NAME}")
                                workerImage.push("latest")
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}
