pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.8.7-openjdk-18-slim
    command: ['sleep']
    args: ['infinity']
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['sleep']
    args: ['infinity']
'''
        }
    }
    stages {
        stage("build") {
            when {
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Compiling worker app..'
                    dir('worker') {
                        sh 'mvn compile'
                    }
                }
            }
        }
        stage("test") {
            when {
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Running unit tests on worker app..'
                    dir('worker') {
                        sh 'mvn clean test'
                    }
                }
            }
        }
        stage("package") {
            when { 
                changeset "**/worker/**"
            }
            steps {
                container('maven') {
                    echo 'Packaging worker app into a jarfile'
                    dir('worker') {
                        sh 'mvn package -DskipTests'
                        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    }
                }
            }
        }
        stage('docker-package') {
            when {
                changeset "**/worker/**"
                branch 'main'
            }
            steps {
                container('kaniko') {
                    echo 'Building and pushing image securely using Kaniko'
                    withCredentials([usernamePassword(credentialsId: 'dockerlogin', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh '''
                            # 1. Create the Docker config.json file so Kaniko can authenticate with Docker Hub
                            mkdir -p /kaniko/.docker
                            AUTH=$(echo -n "$DOCKER_USER:$DOCKER_PASS" | base64 | tr -d '\n')
                            echo "{\\"auths\\":{\\"https://index.docker.io/v1/\\":{\\"auth\\":\\"${AUTH}\\"}}}" > /kaniko/.docker/config.json
                            
                            # 2. Execute the Kaniko build and push both tags simultaneously
                            /kaniko/executor \
                                --context `pwd`/worker \
                                --dockerfile `pwd`/worker/Dockerfile \
                                --destination emmiduh93/worker:v${BUILD_ID} \
                                --destination emmiduh93/worker:latest
                        '''
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}
